
export const CREATE_NEW_ATTRIBUTE = 'CREATE_NEW_ATTRIBUTE';
export const ATTRIBUTE_CHANGED = 'ATTRIBUTE_CHANGED';
export const DATATYPE_CHANGED = 'DATATYPE_CHANGED';
export const CHANGE_ENUMERATIONS_DEFAULT = 'CHANGE_ENUMERATIONS_DEFAULT';
