
export const CREATE_NEW_ATTRIBUTE = 'CREATE_NEW_ATTRIBUTE';
export const ATTRIBUTE_CHANGED = 'ATTRIBUTE_CHANGED';
export const DATATYPE_CHANGED = 'DATATYPE_CHANGED';
export const CHANGE_ENUMERATIONS_DEFAULT = 'CHANGE_ENUMERATIONS_DEFAULT';
export const ADD_ENUMERATION_DATA = 'ADD_ENUMERATION_DATA';
export const CHANGE_DATATYPE_STRING_NUMBER_DEFAULT = 'CHANGE_DATATYPE_STRING_NUMBER_DEFAULT';
export const DELETE_ATTRIBUTE = 'DELETE_ATTRIBUTE';
export const FORM_VALIDATION_ERROR = 'FORM_VALIDATION_ERROR';
export const CLEAR_VALIDATION_ERRORS = 'CLEAR_VALIDATION_ERRORS';
export const DELETE_ENUMERATION_DATA = 'DELETE_ENUMERATION_DATA';
export const VALIDATE_ALL_ATTRIBUTES = 'VALIDATE_ALL_ATTRIBUTES';
export const CLEAR_ALL_ATTRIBUTES_VALIDATION = 'CLEAR_ALL_ATTRIBUTES_VALIDATION';
export const CLEAR_DELETE_ATTRIBUTE_NOTIFICATION = 'CLEAR_DELETE_ATTRIBUTE_NOTIFICATION';
